# Generated by Django 4.2.4 on 2025-02-10 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_board_details_board_is_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=50)),
                ('line_status', models.BooleanField(default=False)),
                ('text_message', models.CharField(choices=[('modify', 'Task Modified'), ('end_date', 'Task End Date'), ('custom', 'Custom Message')], max_length=50)),
                ('date_message', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
