# Generated by Django 4.2.4 on 2025-02-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusermodel_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_notify_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_notify_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_notify_update',
            field=models.BooleanField(default=True),
        ),
    ]
