# Generated by Django 4.2.4 on 2025-02-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customusermodel_is_notify_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='is_notify_create',
            new_name='is_notify_create_board',
        ),
        migrations.RenameField(
            model_name='customusermodel',
            old_name='is_notify_delete',
            new_name='is_notify_create_task',
        ),
        migrations.RenameField(
            model_name='customusermodel',
            old_name='is_notify_update',
            new_name='is_notify_delete_board',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_notify_delete_task',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_notify_update_board',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_notify_update_task',
            field=models.BooleanField(default=True),
        ),
    ]
